# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Account ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, verbose_name='Amount')),
                ('reserved_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, verbose_name='Reserved amount')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, verbose_name='Amount')),
                ('reserved_amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, verbose_name='Reserved amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Account', verbose_name='Account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('status', models.CharField(choices=[('a', 'Authorization'), ('p', 'Presentment'), ('s', 'Money shortage'), ('l', 'Presentment is late')], max_length=1, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=4, default=0.0, max_digits=19, verbose_name='Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Account', verbose_name='Account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processing.Transaction', verbose_name='Transaction')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='accountdaylog',
            unique_together=set([('account', 'day')]),
        ),
    ]
