# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsunion',
            name='role',
            field=models.CharField(choices=[('b', 'Real user'), ('is', 'Inner settlement account'), ('el', 'External load money account'), ('es', 'External settlement account'), ('r', 'Inner revenue account')], default='b', max_length=2, verbose_name='Role'),
        ),
    ]
