# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base64_description',
            field=models.TextField(blank=True, null=True, verbose_name='JSON from schema in base64'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='human_readable_description',
            field=models.TextField(blank=True, null=True, verbose_name='Human readable description'),
        ),
    ]
